@port=8000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imthbm5hQGtvYmF5YXNoaS5jb20iLCJpZCI6MywiY3JlYXRlZF9hdCI6IjIwMjQtMDEtMDFUMjA6MzY6MTMuMDUzMDMzKzAwOjAwIiwidXNlciI6eyJpZCI6MiwidXNlcm5hbWUiOiJLYW5uYSIsImF2YXRhciI6bnVsbCwiZGlzcGxheW5hbWUiOm51bGx9LCJ0eXBlIjoiQmVhcmVyIiwiZXhwaXJlcyI6MTcwNDIyNzg5NDAyNX0.DvpeJl_b_s26FwjUpS6TyqUODmyff9oIzplPu8XS3ss

# @name getCurrent
GET http://localhost:{{port}}/api/users/@me
Content-Type: application/json
Authorization: Bearer {{token}}

###
# @name editCurrent
PATCH http://localhost:{{port}}/api/users/@me
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "displayname": "Kanna Kamui"
}