@port=8000

# @name register
POST http://localhost:{{port}}/api/users/register
Content-Type: application/json

{
    "email": "kanna@kobayashi.com",
    "password": "password"
}

###
# @name create
POST http://localhost:{{port}}/api/users/create
Content-Type: application/json
Authorization: Register eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imthbm5hQGtvYmF5YXNoaS5jb20iLCJpZCI6MywiY3JlYXRlZF9hdCI6IjIwMjQtMDEtMDFUMjA6MzY6MTMuMDUzMDMzKzAwOjAwIiwidHlwZSI6IlJlZ2lzdGVyIiwiZXhwaXJlcyI6MTcwNDIyNzg0ODM1OX0.Kb2rFTz5Exen66RJP8swLBDAN5thR3qyxCMG1PYiQDM

{
    "username": "Kanna"
}