@port=8000

# @name authorize
POST http://localhost:{{port}}/auth/authorize
Content-Type: application/json

{
    "email": "kanna@kobayashi.com",
    "password": "password"
}

###
# @name refresh
POST http://localhost:{{port}}/auth/refresh
Authorization: Register eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imthbm5hQGtvYmF5YXNoaS5jb20iLCJpZCI6MywiY3JlYXRlZF9hdCI6IjIwMjQtMDEtMDFUMjA6MzY6MTMuMDUzMDMzKzAwOjAwIiwidHlwZSI6IlJlZ2lzdGVyIiwiZXhwaXJlcyI6MTcwNDIyNzg0ODM1OX0.Kb2rFTz5Exen66RJP8swLBDAN5thR3qyxCMG1PYiQDM