@port=8000

# @name authorize
POST http://localhost:{{port}}/auth/authorize
Content-Type: application/json

{
    "email": "anya@forger.com",
    "password": "password"
}

###
# @name refresh
POST http://localhost:{{port}}/auth/refresh
Authorization: Register eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFueWFAZm9yZ2VyLmNvbSIsImlkIjoyLCJjcmVhdGVkX2F0IjoiMjAyMy0xMi0zMFQwNzoyODoyMC4yNDQxMzgrMDA6MDAiLCJ0eXBlIjoiUmVnaXN0ZXIiLCJleHBpcmVzIjoxNzA0MDg1NzM2NjExfQ.tlSxYRciWjyi2Lb00aUuaZThJaXaiDtvU8qc-07EpkY